<?php

/**
 * @file
 * Marucha hooks.
 */

/**
 * Implements hook_cron().
 */
function marucha_cron() {
  $title1 = 'Entity APIで作成した記事ですよね';
// test
// APIのエンドポイント
$apiUrl = 'https://api.thecatapi.com/v1/images/search';

// cURLを初期化
$ch = curl_init();

// cURLオプションを設定
curl_setopt($ch, CURLOPT_URL, $apiUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

// リクエストを実行し、レスポンスを取得
$response = curl_exec($ch);

// cURLセッションを閉じる
curl_close($ch);

// レスポンスをJSONデコード
$data = json_decode($response, true);
$title1 = $data[0]['url'];
// end of Test

  // ノードストレージの読み込み
  $nodeStorage = \Drupal::entityTypeManager()->getStorage('node');

  // ID指定でノードエンティティを読み込む
  $node = $nodeStorage->load(1);
  \Drupal::messenger()->addStatus('読み込んだノード: ' . $node->id() . ', ' . $node->getTitle());

  // ノードエンティティの作成と保存

  $newNode = $nodeStorage->create([
    'type' => 'test_type',
    'title' => $title1,
  ]);
  $newNode->save();
  \Drupal::messenger()->addStatus('Entity APIで作成したノード: ' . $newNode->id() . ', ' . $newNode->getTitle());

  // ノードエンティティの削除
  // $newNode->delete();
}